name: base_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
  auto_route: ^5.0.0
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  flutter_svg: ^2.0.2
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  google_fonts: ^4.0.3
  firebase_messaging: ^14.2.5
  json_annotation: ^4.3.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  dio: ^5.0.1
  firebase_dynamic_links: ^5.0.15
  firebase_core: ^2.7.0
  crypto: ^3.0.1
  dartz: ^0.10.0
  responsive_framework: ^0.2.0 
  rflutter_alert: ^2.0.4
  pretty_dio_logger: ^1.1.1
  flutter_phoenix: ^1.0.0
  flutter_dotenv: ^5.0.2
  flavor: ^2.0.0  
  firebase_crashlytics: ^3.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.2
  build_runner: "^2.1.4"
  freezed: ^2.0.3+1
  flutter_launcher_icons: ^0.12.0
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/svgs/
    - assets/icons/
    - assets/env/
